### ISSUE TITLE
Getting Prohibited logo during first Boot Up

### ISSUE THREAD

**Issue by kobid** [29satnam/LenovoHackintoshEFI#1]
I have the same laptop as yours
i5-6gen
ram: 8gb ddr4,
hd 520

i have replaced clover folder with your files and i am getting Getting Prohibited logo during first Boot Up
I am trying to install sierra

**Comment by 29satnam** [comment]
You don't have the same laptop! Mine is 7th Gen i5 Kaby Lake with Intel HD620, that's what makes it different. Use Rehabman's config file for HD520 
Here's the link:
 https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_HD520_530_540.plist
Using this build the whole clover folder from scratch.

**Comment by kobid** [comment]
Could you please send me clover according to my pc i tried multiple Configuration but failed

**Comment by 29satnam** [comment]
Ping me at 29satnam@gmail.com
