### ISSUE TITLE
Ideapad 520 i7 8550u everything works fine but the speaker and trackpad

### ISSUE THREAD

**Issue by MomenMahmoud7** [29satnam/LenovoHackintoshEFI#4]
everything works fine but the speaker (Headphones and HDMI works fine)

trackpad works but it doesn't appear in settings and its keep moving when i move my hand away i have to click again to stop

i don't know how to patch i just tried that efi folder and some kext

Mac OS High Sierra 
EFI folder here: https://drive.google.com/open?id=1d4hkbvmbRTDAyIICQhqI3uSW6pL6GMKu

**Comment by 29satnam** [comment]
Did you try VoodooHDA for Audio?
And I’ve mentioned a fix for trackpad also in the Readme.

**Comment by MomenMahmoud7** [comment]
VoodooHDA is what i am using and the headphone and hdmi only what works speaker doesn't appear in audio settings 
Speakers is alc0230

and i tried that fix for trackpad and didn't work

trackpad is not found in settings but it work 
trackpad is synaptics clickpad
